# Generated by Django 5.0.6 on 2025-04-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpicture',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the image if no file is uploaded', null=True),
        ),
        migrations.AlterField(
            model_name='artpicture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='art_pictures/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('admin_to_user', 'Admin to User'), ('admin_to_all', 'Admin to All Users'), ('user_to_admin', 'User to Admin')], max_length=20),
        ),
    ]
