# Generated by Django 5.0.6 on 2025-04-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_address_alter_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_details',
            field=models.JSONField(blank=True, help_text='Additional payment details (e.g. PayPal transaction data)', null=True),
        ),
    ]
