# Generated by Django 5.0.6 on 2025-05-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_create_order_user_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUserView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_number', models.UUIDField()),
                ('status', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_details', models.JSONField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('shipping_address_obj_id', models.IntegerField(null=True)),
                ('billing_address_obj_id', models.IntegerField(null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('display_name', models.CharField(max_length=301)),
            ],
            options={
                'db_table': 'api_order_user_view',
                'ordering': ['username', '-created_at'],
                'managed': False,
            },
        ),
    ]
